use Useful;

# Copyright: Judita Preiss
# Date of creation: 11 September 2011

use XML::RSS::Parser::Lite;
use LWP::UserAgent;

# This program attempts to avoid the problems generated by the Perl
# XML::RSS module: this module cannot cope with even very simple RSS
# errors and causes failure. This program therefore is allowed to fail
# if the module fails and the wrapper picks up failure from this
# program.

(scalar(@ARGV) == 2) or die "Args: type url\n";

$type = $ARGV[0];

sub read_file {
    my ($html, $file);

    (scalar(@_) == 1) or die "read_file: file\n";
    $file = $_[0];

    open(INPUT, $file) or die "Can't open $file: $!\n";
    
    $html = "";
    
    while($line = <INPUT>){

	chomp($line);

	$html .= " " . $line;
    }

    close(INPUT);

    $html = remove_multiple_spaces($html);

    return $html;
}

if($type eq "file"){
    my $rss = new XML::RSS::Parser::Lite;
    $html = read_file($ARGV[1]);
    $rss->parse($html);
}
elsif($type eq "url"){ 
    my $rss = new XML::RSS::Parser::Lite;
    my $html = get_url($ARGV[1]);
    $rss->parse($html);
}
else{
    die "Unexpected type: $type\n";
}
